// File generated by FlutterFire CLI (updated for Android + Web).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web; // Web configuration added
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - run FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - run FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - run FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - run FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔹 Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeYiR6Ow1_5TyIUmHN5O9PK0GZj13j1O0',
    appId: '1:719664018759:android:c7c8e9ab9b41ca0c400862',
    messagingSenderId: '719664018759',
    projectId: 'smarshop-7bfc2',
    storageBucket: 'smarshop-7bfc2.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3HnN3X-something-real-key',
    appId: '1:719664018759:web:ab12cd34ef56gh78ij90kl',
    messagingSenderId: '719664018759',
    projectId: 'smarshop-7bfc2',
    storageBucket: 'smarshop-7bfc2.appspot.com',
  );

}
